import type { Metadata } from "next";
import { Libre_Baskerville, League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const fontLibreBakersville = Libre_Baskerville({
  subsets: ["latin"],
  weight: "400",
});
export const fontLeagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Selfiebooth Guam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontLibreBakersville.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
