import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import { fontLibreBakersville } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Selfiebooth Guam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontLibreBakersville.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
