import type { Metadata } from "next";
import "../globals.css";
import Navbar from "../_components/Navbar";
import { fontLibreBakersville } from "@/lib/fonts";
import { ThemeProvider } from "../_components/ThemeProvider";
import Footer from "../_components/Footer";

export const metadata: Metadata = {
  title: "Selfiebooth Guam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale}>
      <body className={fontLibreBakersville.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
