import { inter } from "@/lib/fonts";
import type { Metadata } from "next";
import Footer from "../_components/Footer";
import Navbar from "../_components/Navbar";
import { ThemeProvider } from "../_components/ThemeProvider";
import "../globals.css";

export const metadata: Metadata = {
  title: "Selfiebooth Guam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} className="scroll-smooth bg-background">
      <head>
        <link
          rel="alternate"
          hrefLang="jp"
          href="https://www.selfieboothguam.com/jp"
        />
      </head>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
